---
version: 1
datastore:
  filename: data.json
scheduler:
  interval: 5
eventstores:
  track_locations:
    url: http://localhost:8090/track/locations
  track_alerts:
    url: http://localhost:8090/track/alerts